pipeline {
    agent any

    environment {
        EC2_HOST = 'ubuntu@98.82.11.52'
        SSH_CREDENTIALS_ID = 'ec2-ssh'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/mrunallabhe/Airline-Management-.git'
            }
        }

        stage('Build with Docker Maven') {
            steps {
                script {
                    docker.image('maven:3.9.6-eclipse-temurin-21').inside {
                        sh 'mvn clean package -DskipTests'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image('maven:3.9.6-eclipse-temurin-21').inside {
                        sh 'mvn test'
                    }
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(credentials: [env.SSH_CREDENTIALS_ID]) {
                    sh """
                        scp target/*.jar ${EC2_HOST}:/home/ubuntu/app.jar
                        ssh ${EC2_HOST} 'nohup java -jar /home/ubuntu/app.jar > app.log 2>&1 &'
                    """
                }
            }
        }
    }

    post {
        failure {
            echo "❌ Build or deployment failed."
        }
        success {
            echo "✅ Application deployed successfully!"
        }
    }
}
