pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-21'
            args '-v /root/.m2:/root/.m2'
        }
    }

    environment {
        EC2_HOST = '98.82.11.52' // Your EC2 IP
        EC2_USER = 'ubuntu'
        JAR_NAME = 'airline-management-0.0.1-SNAPSHOT.jar' // Change if needed
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/mrunallabhe/Airline-Management-.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package -DskipTests=false'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent (credentials: ['ec2-ssh']) {
                    sh """
                        scp -o StrictHostKeyChecking=no target/${JAR_NAME} ${EC2_USER}@${EC2_HOST}:/home/ubuntu/
                        ssh ${EC2_USER}@${EC2_HOST} 'nohup java -jar /home/ubuntu/${JAR_NAME} > app.log 2>&1 &'
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ App successfully deployed at http://${EC2_HOST}:8080"
        }
        failure {
            echo "❌ Something went wrong during build or deployment!"
        }
    }
}
