pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-21'
        }
    }
    environment {
        JAR_NAME = "airline-management-system-0.0.1-SNAPSHOT.jar"
        EC2_USER = "ec2-user"
        EC2_HOST = "34.203.217.45"
        PEM_FILE = "/root/.ssh/springboot.pem"  // mounted into the container
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/mrunallabhe/Airline-Management-.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy to EC2') {
            steps {
                sh """
                    chmod 400 $PEM_FILE
                    scp -o StrictHostKeyChecking=no -i $PEM_FILE target/$JAR_NAME $EC2_USER@$EC2_HOST:/home/ec2-user/
                    ssh -o StrictHostKeyChecking=no -i $PEM_FILE $EC2_USER@$EC2_HOST "nohup java -jar /home/ec2-user/$JAR_NAME > app.log 2>&1 &"
                """
            }
        }
    }
}
